# Generated by Django 4.0.2 on 2022-03-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actores',
            name='CargoA',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
