# Generated by Django 4.0.2 on 2022-03-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_actores_cargoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoB', models.CharField(default='link', max_length=200)),
                ('tituloB', models.CharField(max_length=200)),
                ('fechaB', models.CharField(max_length=100)),
                ('nombreAu', models.CharField(max_length=200)),
                ('escritoB', models.CharField(max_length=1000)),
            ],
        ),
    ]
